apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- name: quay.io/upslopeio/express-sample-app
  newName: quay.io/mhillb/express-sample-app
  newTag: eb71aee7da983cdd00a9e230de964fda41d82d1f
commonLabels:
  app.kubernetes.io/instance: express-sample-app
  app.kubernetes.io/name: express-sample-app
